### ISSUE TITLE
Cannot login after adding users

### ISSUE THREAD

**Issue by curlyjason** [OrigamiStructures/foldingTime#3]
I think I'm having the same issues with login via Auth. I am unable to login after creating a new user. I think this is something that we resolved in the past, but I cannot think of the solution now.

**Comment by dreamingmind** [comment]
Is this a problem with the change in encryption in 3x? The new way is that weird mutating password that is handled in the background and the 2x what used simple sha1 or something.

**Comment by dreamingmind** [comment]
There is some possibility that the password field is not long enough to work. In simpleblog we opened it up to 255. Right now it is 40. I don't know what the length is for the current default hash scheme for cake 3

**Comment by curlyjason** [comment]
Extension of the password field solved the problem.
